### ISSUE TITLE
Be able to set environment variables in config/profiles

### ISSUE THREAD

**Issue by edoyango** [WEHI-ResearchComputing/ToolParameteriser#19]
Environment variables can be passed to `sbatch` by
```
sbatch --export=ENVVAR1=123,ENVVAR2=abc
```
so a config item could be 
```
[jobs]
qos = "regular"
...
environment = "ENVVAR1=123,ENVVAR2=abc"
```
and that could be passed directly to `sbatch`. Similarly, a per-job list of environment variables can be passed with an "environment" column:
| jobname | cpuspertask | ... | environment |
| --- | --- | --- | --- |
| job1 | 2 | ... | "ENVVAR1=123,ENVVAR2=abc" |
| job2 | 4 | ... | "ENVVAR1=456,ENVVAR2=def" |

Alternatively, we have seperate items like
```
[environment]
ENVVAR1 = "123"
ENVVAR2 = "abc"
```
or in the profile:
| jobname | cpuspertask | ... | ENVVAR1 | ENVVAR2 |
| --- | --- | --- | --- | --- |
| job1 | 2 | ... | 123 | abc |
| job2 | 4 | ... | 456 | def |

Probably requires more parsing logic though

**Comment by jIskCoder** [comment]
@edoyango  Was just testing and got this error

toolparameteriser

Traceback (most recent call last):
  File "/stornext/System/data/apps/rc-tools/rc-tools-1.0/bin/tools/ProteinHallucination/envs/testtoolparam/bin/toolparameteriser", line 5, in <module>
    from toolparameteriser.run import main
  File "/stornext/System/data/apps/rc-tools/rc-tools-1.0/bin/tools/ProteinHallucination/envs/testtoolparam/lib/python3.11/site-packages/toolparameteriser/run.py", line 2, in <module>
    import toolparameteriser.testcreator
  File "/stornext/System/data/apps/rc-tools/rc-tools-1.0/bin/tools/ProteinHallucination/envs/testtoolparam/lib/python3.11/site-packages/toolparameteriser/testcreator.py", line 69
    if 'environment' not in params.keys():
TabError: inconsistent use of tabs and spaces in indentation

**Comment by edoyango** [comment]
@jIskCoder 
My bad. I fixed it in the most recent commit. Can you try again?
